<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD Rubrica Telefonica</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div style="margin-top: 5%;" class="panel panel-default">
                <div class="panel-heading">Rubrica Telefonica</div>
                <div class="panel-body">
                    <form action="" method="post" role="form">
                        <div class="form-group">
                            <label for="">Nome & Cognome</label>
                            <input type="text" class="form-control" name="fullname" id="" required="">
                        </div>
                        <div class="form-group">
                            <label for="">Numero di Telefono</label>
                            <input type="text" class="form-control" name="phone" id="" required="">
                        </div>
                        <button type="submit" class="btn btn-primary">SALVA</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>